### ISSUE TITLE
Error during Validation: ValueError: shapes (2,2,1) and (2,4) not aligned: 1 (dim 2) != 2 (dim 0)

### ISSUE THREAD

**Issue by JJayaL** [WangShaoSUN/grasp-transformer#16]
INFO:root:Beginning Epoch 00
current lr: 0.0001
INFO:root:Epoch: 0, Batch: 10, Loss: 0.4166
INFO:root:Epoch: 0, Batch: 20, Loss: 0.1777
INFO:root:Epoch: 0, Batch: 30, Loss: 0.1597
INFO:root:Epoch: 0, Batch: 40, Loss: 0.1461
INFO:root:Epoch: 0, Batch: 50, Loss: 0.1125
INFO:root:Epoch: 0, Batch: 60, Loss: 0.1917
INFO:root:Epoch: 0, Batch: 70, Loss: 0.1286
INFO:root:Epoch: 0, Batch: 80, Loss: 0.1242
INFO:root:Epoch: 0, Batch: 90, Loss: 0.1689
INFO:root:Epoch: 0, Batch: 100, Loss: 0.0970
INFO:root:Epoch: 0, Batch: 110, Loss: 0.0530
INFO:root:Epoch: 0, Batch: 120, Loss: 0.0884
INFO:root:Epoch: 0, Batch: 130, Loss: 0.1711
INFO:root:Epoch: 0, Batch: 140, Loss: 0.0844
INFO:root:Epoch: 0, Batch: 150, Loss: 0.1038
INFO:root:Epoch: 0, Batch: 160, Loss: 0.1011
INFO:root:Epoch: 0, Batch: 170, Loss: 0.1339
INFO:root:Epoch: 0, Batch: 180, Loss: 0.0725
INFO:root:Epoch: 0, Batch: 190, Loss: 0.1152
INFO:root:Epoch: 0, Batch: 200, Loss: 0.1178
INFO:root:Validating...
Traceback (most recent call last):
  File "/home/jjayalekshmi/workspaces/grasp-transformer/main.py", line 110, in <module>
    run()
  File "/home/jjayalekshmi/workspaces/grasp-transformer/main.py", line 98, in run
    test_results = validate(net, device, val_data, args.val_batches)
  File "/home/jjayalekshmi/workspaces/grasp-transformer/traning.py", line 53, in validate
    val_data.dataset.get_gtbb(didx, rot, zoom_factor),
  File "/home/jjayalekshmi/workspaces/grasp-transformer/utils/data/cornell_data.py", line 48, in get_gtbb
    gtbbs.rotate(rot, center)
  File "/home/jjayalekshmi/workspaces/grasp-transformer/utils/dataset_processing/grasp.py", line 42, in <lambda>
    return lambda *args, **kwargs: list(map(lambda gr: getattr(gr, attr)(*args, **kwargs), self.grs))
  File "/home/jjayalekshmi/workspaces/grasp-transformer/utils/dataset_processing/grasp.py", line 42, in <lambda>
    return lambda *args, **kwargs: list(map(lambda gr: getattr(gr, attr)(*args, **kwargs), self.grs))
  File "/home/jjayalekshmi/workspaces/grasp-transformer/utils/dataset_processing/grasp.py", line 316, in rotate
    self.points = ((np.dot(R, (self.points - c).T)).T + c).astype(int)
ValueError: shapes (2,2,1) and (2,4) not aligned: 1 (dim 2) != 2 (dim 0)

**Comment by xiaoming-gong** [comment]
I'm having the same issue, have you solved it now?

**Comment by xiaoming-gong** [comment]
> Reference in

Using python 3.8 and numpy 1.21.1 can solve this problem.
