### ISSUE TITLE
Couldn't find function center in BoundingBoxes or BoundingBox

### ISSUE THREAD

**Issue by muthukumarpandaram** [WangShaoSUN/grasp-transformer#8]
I keep getting this error that it could not find the function center but I see it being there in the under the  GraspRectangle class
 when I try to train the Cornell grasp dataset using the main.py
```
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/ali/grasp-transformer/env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/ali/grasp-transformer/env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/ali/grasp-transformer/env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/ali/grasp-transformer/utils/data/grasp_data.py", line 69, in __getitem__
    rgb_img = self.get_rgb(idx, rot, zoom_factor)
  File "/data/ali/grasp-transformer/utils/data/cornell_data.py", line 69, in get_rgb
    center, left, top = self._get_crop_attrs(idx)
  File "/data/ali/grasp-transformer/utils/data/cornell_data.py", line 43, in _get_crop_attrs
    center = gtbbs.center
  File "/data/ali/grasp-transformer/utils/dataset_processing/grasp.py", line 44, in __getattr__
    raise AttributeError("Couldn't find function %s in BoundingBoxes or BoundingBox" % attr)
AttributeError: Couldn't find function center in BoundingBoxes or BoundingBox

```

**Comment by muthukumarpandaram** [comment]
It was an issue with numpy versions>=1.24.0 where the numpy doesnot have attributes like int or float. 
This was triggered by the return line in the center method:
```
@property
def center(self):
    """
    :return: Rectangle center point
    """
    return self.points.mean(axis=0).astype(np.int)
```
The issue was solved by using a numpy version < 1.24.0
